### ISSUE TITLE
Разделить на части

### ISSUE THREAD

**Issue by MitinSany** [k-samuel/dvelum#117]
Предлагаю в будущем "переорганизовать" род на отдельные самостоятельные или слабо-зависимые компоненты. Например ORM, модуль acl, приложение/рендер extjs

**Comment by k-samuel** [comment]
Добрый день. Спасибо за предложение.
Постепенно движемся в этом направлении.

**Comment by MitinSany** [comment]
хотелось бы какую-то библиотеку, которая была современная (использовала бы ExtJS 4 и выше), была бы норм документирована (понимаю, что это очень опционально) и была бы аналогом php-ext или ExtGWT только для php, чтобы потенциальный разработчик не вникал в дебри екста, а сконцентрировался на написании php кода
