### ISSUE TITLE
Вывод отработки PHP-кода на страницах

### ISSUE THREAD

**Issue by e-v-medvedev** [k-samuel/dvelum#130]
Как можно вывести результат отработки PHP кода на странице, например в разделе content или в заголовке? При вводе в поле текста на странице php код экранируется.

**Comment by k-samuel** [comment]
Доброго времени суток. Не понял что вы имеете в виду. Возможно этот матиал из документации вам поможет: https://dvelum.ru/cookbook_simple_module.html.
Если вы о том, что  html  тэги экранируются, то в  ORM  настройках поля есть опция "разрешить  html"

**Comment by e-v-medvedev** [comment]
Просто возник вопрос, как например в области content на главной странице вывести результат выполнения простейшего PHP-скрипта.
Например если нужно вывести какой-нибудь виджет со списком последний статей блога, или какой то контент по результатам обработки входной строки.
В различных платформах есть хелперы, которые выполняют простейшие функции, результат которых вставляется в HTML код страницы. А здесь пока нашел что все делается через создание модулей со своими контроллерами и т.п.
Могу я написать свой блок, состоящий из чистого PHP-кода, результат работы которого выведется так, куда этот блок вставлен? Пока нашел, что блок можно редактировать только как html код.
Еще возник вопрос как на на какой то специфической странице добавить свои JS и CSS файлы, да так, чтобы они тоже кэшировались? Как я это могу сделать из блока? (ведь обычно именно блок тащит за собой специфический код для клиента).

**Comment by k-samuel** [comment]
**Вариант 1** блоки
 https://dvelum.ru/guide_blocks.html  они могут быть 3х видов:
- html
- меню
- php  код. 
В последнем случае вы создаете свой класс наследник  Block. В интерфейсе управления блоками создаете новую запись, ставите галку  "системный",  выбираете ваш класс блока из списка.
Блоки передают данные в свои шаблоны. В блоках так же можно подключать js и css  через  Resource::getInstance() или шаблон.

**Вариант 2** прикрепить к странице функциональность https://dvelum.ru/guide_pages.html
Вы описываете модуль (контроллер) и прикрепляете его к странице, как показано в примере с новостями  https://dvelum.ru/cookbook_simple_module.html.
Для этого нужно описать контроллер объявить его модулем публичной части, в одноименном разделе. Зайти в интерфейс управления страницами, подключить к странице ваш модуль.

**Вариант 3** передать данные в шаблон нужной темы оформления

Подключить свои  JS  и  CSS  можно в контроллере используя  $this->_resource  (Resource)
Или в конкретном шаблоне используя  html

**Comment by e-v-medvedev** [comment]
А где должны размещаться файлы классов блоков по структуре кода в соответствии с феншуй Dvelumа? Они сами подключаются или их нужно в автолоадере прописывать? Композером я так понимаю пока ни чего не грузится? Это в следующей версии.

**Comment by k-samuel** [comment]
Феншуй: My_Class_Name =  application/controllers/My/Class/Name.php  или application/library/My/Class/Name.php

Например: class Block_News лучше положить в   application/controllers/Block/News.php
Autoloader сам найдет нужный класс.
Composer  поддерживается в  2.0.0, но эта версия еще в альфе

**Comment by e-v-medvedev** [comment]
C application/library  не прошло. Создал файл в application/library/Namespace/Block/Test.php. В нем класс Namespace_Block_Test extends Block . В классе прописал метод render, возвращающий просто строку. Но в списке классов при создании блока этот класс не виден.

**Comment by e-v-medvedev** [comment]
Вообще ни из одной папки не видит система класса. Пробовал положить его и в dvelum/app/Block. Добавил его и в application/configs/dist/classmap.php. Не помогло.

**Comment by k-samuel** [comment]
application/controllers/Block/Test.php не виден ?

**Comment by e-v-medvedev** [comment]
Отсюда тоже виден. Не виден только если я в этих папках создаю подкаталог Namespace, а уже в нем Block/Test.php

**Comment by k-samuel** [comment]
С блоками особенность, они должны лежать в папке Block далее уже любая вложенность

**Comment by e-v-medvedev** [comment]
Такая схема менее удобна. Обычно схема такая Namespace/Modulename/(Block|Controller|Model)/Filename.php .

**Comment by k-samuel** [comment]
Так сделано для сторонних модулей. Для локальных пока через папку Blocks, постараемся что-нибудь придумать к версии 2.0
