### ISSUE TITLE
Меню добавление, редактирование

### ISSUE THREAD

**Issue by andriusphoto** [k-samuel/dvelum#133]
Добрый день,
создавая или редактируя меню элемент, выбрав тип ссылки "страница", список даступных страниц пустои, хатя их есть.

**Comment by k-samuel** [comment]
Добрый день, спасибо за отклик. Удалось воспроизвести проблему в последнем релизе. В ближайшее время внесу правки. Временно обойти проблему при помощи функции импорт элементов меню из структуры сайта (import from site structure)

**Comment by k-samuel** [comment]
Исправление внесено в master ветку.
