### ISSUE TITLE
Добавление папки загрузки классов на примере блоков

### ISSUE THREAD

**Issue by andriusphoto** [k-samuel/dvelum#134]
Добрый день,
создал свои блок класс, положил в application/Bloacks/, прописал в классмапе, неработает.
Тотже вариант в /dvelum/app/Block/  работает. Хателась бы в application.

**Comment by k-samuel** [comment]
Добрый день. В классмап вручную не нужно ничего вписывать, карта классов собирается автоматически в интерфейсе управления модулями (перестроить карту классов). Более того карта отключена по умолчанию.

Для того чтобы блоки работали в  application:
создаем папку  application/blocks/Block

переопределяем настройки загрузки классов, копируем  раздел  autoloader  из  application/configs/dist/main.php  в  application/configs/local/main.php 
и добавляем туда папку для автозагрузки, получатся  настройки вида

```php
<?php return array (
  'salt' => '....',
  'development' => 1,
  'timezone' => 'UTC',
  'adminPath' => 'backoffice',
  'language' => 'en',
  'wwwroot' => '/',
    'autoloader' => array(
        'paths' => array(
            './application/controllers',
            './application/models',
            './application/library',
            './application/blocks',  // <======== Ваша папка для автозагрузки
            './dvelum/app',
            './dvelum/library',
            './vendor'
        ),
        'priority'=>[
            './application/controllers',
            './application/models',
            './application/library',
        ],
        'useMap' => false,  // <===== Включение карты классов (ускорение)
        'map' => 'classmap.php',
        'plugins' =>[ /*...*/],
    ),
);
 ```

Теперь в  application/blocks/Block
Можно складывать классы вида  с  именованием вида  Block_News

**Comment by andriusphoto** [comment]
Большое спасибо за быстрый ответ!

**Comment by andriusphoto** [comment]
все таки система не реагирует на эти изменения в application/configs/local/main.php, толка на classmap.php (поставлена 'useMap' => false, )

**Comment by k-samuel** [comment]
Видимо что то у вас с настройками. Я проверил прежде чем ответить вам. Попробуйте пересобрать карту классов  сбросить opcache если установлен

**Comment by k-samuel** [comment]
Перепроверю
