### ISSUE TITLE
Добавление папки загрузки классов на примере блоков #134

### ISSUE THREAD

**Issue by andriusphoto** [k-samuel/dvelum#135]
https://github.com/k-samuel/dvelum/issues/134
все таки система не реагирует на эти изменения в application/configs/local/main.php, толка на classmap.php (поставлена 'useMap' => false, )

**Comment by k-samuel** [comment]
Перепроверил, не удалось воспроизвести проблему.
Попробуйте следуя совету в #134
Создать файл applicaction/blocks/Block/News.php  в файле класс class Block_News extends Block_Simple{}   
Зайдите в интерфейс управления блоками,  создать новый блок, поставьте галку  attached functionality,  в списке должен появиться ваш класс Block_News

**Comment by andriusphoto** [comment]
Понел, ето из-за того что я ложил applicaction/blocks/News.php а надо била applicaction/blocks/Block/News.php

**Comment by andriusphoto** [comment]
Спасибо за помощь!

**Comment by k-samuel** [comment]
Отлично.  В таком случае задачу закрываю. Обращайтесь, если что-то будет непонятно.
