### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by andriusphoto** [k-samuel/dvelum#137]
Добрый день,
питаус разобратся, роутерам. 
Мне надо стобе при назатие на линк добавлялис параметри в стиле "param1/value1"
находится в таком site.com/controlerName/actionName/param0/value0/
$url->add('param1','value1') виводит site.com/controlerName/actionName/param0/value0/param1/value1
и потом например
$url->set('param1','value2') 
site.com/controlerName/actionName/param0/value0/param1/value2
и потом например
$url->get('param1')  //value2

Может ест какои  класс для создании такова фунцтионала?

**Comment by k-samuel** [comment]
Добрый день.
```PHP
Request::url([
     'controlerName',      
     'actionName', 
     'param1value' 
     'param2value' 
]);
```

Чтобы потом получить эти данные из запроса:
```PHP
$request = Request::getInstance();

//controlerName
$request->getPart(0);

//actionName
$request->getPart(1);

//param1value
$request->getPart(2);

//param2value
$request->getPart(3);
```
Нужно учитывать что в админ панели индексы частей url  сместятся на  +1

**Comment by andriusphoto** [comment]
А в ORM "Unique group" мозно правирят уникальнаст из нескалиь таблиц. 
например:
category.slug
company.slug
post.slug
далжни бит уникальнуми (category.slug=''value1' && company.slug=''value1' //The Field value should be unique)

**Comment by andriusphoto** [comment]
Что-то не так спросил? :)

**Comment by k-samuel** [comment]
Да, можно указать одну уникальную группу у нескольких полей. Это аналог уникального составного индекса с валидацией на стороне php

**Comment by andriusphoto** [comment]
а одну групу для полеи в разних таблицах?

**Comment by k-samuel** [comment]
Группу полей можно создать только в рамках одного  ORM  объекта  (оной таблицы)
