### ISSUE TITLE
Block

### ISSUE THREAD

**Issue by andriusphoto** [k-samuel/dvelum#139]
Добрый день,
как передать параметр из контроллера блоку?

**Comment by k-samuel** [comment]
Добрый день. В  DVelum  версии  1.x  в блоки можно передавать только статические параметры, это делается в интерфейсе управления блоками.
Блоки - самостоятельные сущности, которые могут сами брать необходимые данные, например анализировать  url  страницы.  Код получния параметров лучше описать в самом классе блока.

**Comment by andriusphoto** [comment]
Да но тогда получается лишняя обращение к БД

**Comment by k-samuel** [comment]
Можно использовать Registry или Store_Local  для переброса данных

**Comment by andriusphoto** [comment]
папробуу использовать Registry
