### ISSUE TITLE
репортс

### ISSUE THREAD

**Issue by andriusphoto** [k-samuel/dvelum#140]
добрий день,
репортс получаю ошибку:
{"success":false,"msg":"Invalid request. \/valdymas\/savefield","errors":false}
https://1drv.ms/v/s!AoddPYjCSPUuhmkZjstODQW-O9zZ

**Comment by k-samuel** [comment]
Спасибо за багрепорт. Постараюсь исправить

**Comment by k-samuel** [comment]
Добавил исправление. Дайте знать, если все в порядке.

**Comment by k-samuel** [comment]
Закрываю Issue?

**Comment by andriusphoto** [comment]
ok
